version: "3.8"
services:
  backend:
    image: articles
    build: ./articles
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./articles/db:/app/db/
      - ./articles/articles:/app/articles
