version: "3.8"
services:
  articles:
    image: articles
    build: ./articles
    restart: always
    volumes:
      - ./articles/db:/app/db/
      - ./articles/articles:/app/articles
  proxy:
    image: proxy
    build: ./proxy
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - articles
